apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: neobank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ECR_REGISTRY/neobank-backend:latest
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: neobank-config
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: neobank-secrets
                  key: DATABASE_URL
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: neobank-secrets
                  key: REDIS_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: neobank-secrets
                  key: JWT_SECRET
            - name: JWT_REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  name: neobank-secrets
                  key: JWT_REFRESH_SECRET
            - name: JWT_EXPIRATION
              valueFrom:
                secretKeyRef:
                  name: neobank-secrets
                  key: JWT_EXPIRATION
            - name: JWT_REFRESH_EXPIRATION
              valueFrom:
                secretKeyRef:
                  name: neobank-secrets
                  key: JWT_REFRESH_EXPIRATION
            - name: FRONTEND_URL
              value: "http://localhost"
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
